language: node_js
node_js:
- '4.1'
before_script:
- jspm install
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
env:
  global:
    secure: xoHNFKDkyuYji+UGzuvYtWWID9gEduCmklTpzc0lw3aZDpmtFusTDyrASamwYBvp3JSWNy088s7Q7BSR1O/kmlIxKUHNZSsf5dg0jh9bIUTRHTizbFpLmiTPMgj14FRXGoCCVbWeYuCeopI+BTC6UmlXgcEp63xozJqYm/VpN44BsDpOI1LvxxGnjDX4U7HGi8/c26qWL8PnBo6q64y26UOGlC3vpcOhVR738r8kXEEtrE6rbt49iuypOPWGcfv3EdSKMUHbGTAXf6qbGCxuUQ/E6+b8Fyf6fxpSLm33LSyrNGJ9AZJ4sS2c3fdAwGmQUZiHN1c4+rlLn6mwOBhY7djjLakLKWlMZQrUnBJygzZGGvkl8s4Dkc0JiGh39+jslink8qSQviXJVs75ygn30yO9elxZoWoLLuoQAWnutz3iiNBtxKijbG8vd9w1XSRaenhgkke0NgFcSzZa3/h+ShnftFW5FmcUBGex6JvWayWZpnk5A1oV9bViGsi+kJlZ2G3JB/5ZceKg8/VIQt19DdfLe5DmBXNGld1n61cW72U1rfhObxJ8Qo7M6KH2d6fKasc1xwY7Zay6aaAFLFPYcrzbW7epzwgjrB3Kdm0tcgdPlrrXJ3YFjanN8W+Y9vpWUxNBqkfh4Fh7OvkdTzXTs4V+mtCpcpWhCQB+OEmVWTQ=
