language: node_js
node_js:
- '4.1'
install:
- npm install
script:
- npm test
before_deploy:
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- NODE_ENV=production
deploy:
  provider: npm
  api_key:
    secure: Y14iewpaVwLxu0zFEf3ZWBDdpVKZ5Z/Q39ATuGDeZFSNuii5HzVCQvczZLTHr948h/S+863yVLK3jPzc1dcal/Mw1FaU+DvHLwsO4TMjSmKboB2rrSdPrUCG/dgoX50c5+EAKw8cMnkHH5yc89GSPaRhALyTCX5cFWFrB2rnZzJ25GNmJT5q2B8iMt6BQ3lArTSiKN9rmNhLdoB/J7maKnb3IXhkmHowXDwKQSuEAumLLqIoZxsL2qlygbGy6+6ET6+6maTyuYJVmLXwpJ6QB8df5Yx9xK476tFJQHbQKegMdiwXp07BtUc4+KJa6jPFzrZHCGRfXMYx5bsAj5Xv0veai45aVG0MPmo3JYpqXqCQ8YCF2335ND2kdSTrZ1HY1z0ao+q4xX5kaGHjEiOw3gSMmGrPIn1Upa7B6ba68wnvt/WptD8rBHH/7pwQ8PvrTv+LYNWztOdKhE/2jZ5dJr2hHh+dwC5CiiI0Zc4IVFTn17tYid0ysJtZaQwpBQv50/3zy756zhMTMqYb72sO5g+UKg5xFxkFjDUDcPh69yp8oWd/A5b7k0922MbWKsGgWbpCck7v5cgARBXsy8cq2rNma8W+KRSvVaCGBIUaHOt4mJ2wme15XDDLVPpgYrGJIazoTo90tRUKs53OgwbtWveJYmdz6CY9le+APCDMcfg=
  on:
    tags: true
env:
  global:
    secure: xoHNFKDkyuYji+UGzuvYtWWID9gEduCmklTpzc0lw3aZDpmtFusTDyrASamwYBvp3JSWNy088s7Q7BSR1O/kmlIxKUHNZSsf5dg0jh9bIUTRHTizbFpLmiTPMgj14FRXGoCCVbWeYuCeopI+BTC6UmlXgcEp63xozJqYm/VpN44BsDpOI1LvxxGnjDX4U7HGi8/c26qWL8PnBo6q64y26UOGlC3vpcOhVR738r8kXEEtrE6rbt49iuypOPWGcfv3EdSKMUHbGTAXf6qbGCxuUQ/E6+b8Fyf6fxpSLm33LSyrNGJ9AZJ4sS2c3fdAwGmQUZiHN1c4+rlLn6mwOBhY7djjLakLKWlMZQrUnBJygzZGGvkl8s4Dkc0JiGh39+jslink8qSQviXJVs75ygn30yO9elxZoWoLLuoQAWnutz3iiNBtxKijbG8vd9w1XSRaenhgkke0NgFcSzZa3/h+ShnftFW5FmcUBGex6JvWayWZpnk5A1oV9bViGsi+kJlZ2G3JB/5ZceKg8/VIQt19DdfLe5DmBXNGld1n61cW72U1rfhObxJ8Qo7M6KH2d6fKasc1xwY7Zay6aaAFLFPYcrzbW7epzwgjrB3Kdm0tcgdPlrrXJ3YFjanN8W+Y9vpWUxNBqkfh4Fh7OvkdTzXTs4V+mtCpcpWhCQB+OEmVWTQ=