language: node_js
node_js:
- '4.1'
install: # install NPM dependencies
- npm install
script: # run tests
- npm run test
before_deploy: # install JSPM dependencies and create the bundle and the doc
- jspm config registries.github.auth $GITHUB_AUTH_TOKEN
- jspm install
- NODE_ENV=production
- npm run build
- npm run doc
deploy:
- provider: releases #add bundle and documentation to master
  api_key: $GITHUB_AUTH_TOKEN
  file:
  - "dist/ella.js"
  - "doc/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm # publish bundle on NPM
  api_key:
    secure: Y14iewpaVwLxu0zFEf3ZWBDdpVKZ5Z/Q39ATuGDeZFSNuii5HzVCQvczZLTHr948h/S+863yVLK3jPzc1dcal/Mw1FaU+DvHLwsO4TMjSmKboB2rrSdPrUCG/dgoX50c5+EAKw8cMnkHH5yc89GSPaRhALyTCX5cFWFrB2rnZzJ25GNmJT5q2B8iMt6BQ3lArTSiKN9rmNhLdoB/J7maKnb3IXhkmHowXDwKQSuEAumLLqIoZxsL2qlygbGy6+6ET6+6maTyuYJVmLXwpJ6QB8df5Yx9xK476tFJQHbQKegMdiwXp07BtUc4+KJa6jPFzrZHCGRfXMYx5bsAj5Xv0veai45aVG0MPmo3JYpqXqCQ8YCF2335ND2kdSTrZ1HY1z0ao+q4xX5kaGHjEiOw3gSMmGrPIn1Upa7B6ba68wnvt/WptD8rBHH/7pwQ8PvrTv+LYNWztOdKhE/2jZ5dJr2hHh+dwC5CiiI0Zc4IVFTn17tYid0ysJtZaQwpBQv50/3zy756zhMTMqYb72sO5g+UKg5xFxkFjDUDcPh69yp8oWd/A5b7k0922MbWKsGgWbpCck7v5cgARBXsy8cq2rNma8W+KRSvVaCGBIUaHOt4mJ2wme15XDDLVPpgYrGJIazoTo90tRUKs53OgwbtWveJYmdz6CY9le+APCDMcfg=
  on:
    tags: true
after_deploy: # upload doc to gh-pages
- cd doc
- git init
- git config user.name "Travis CI"
- git config user.email "mail@lars-reimann.eu"
- git add .
- git commit -m "Deploying to GitHub Pages"
- git push -fq "https://$GITHUB_AUTH_TOKEN@github.com/Ignavia/js-ella" master:gh-pages > /dev/null 2>&1