window.esdocSearchIndex = [
  [
    "@ignavia/ella/src/vec2.js~vec2",
    "class/src/Vec2.js~Vec2.html",
    "<span>Vec2</span> <span class=\"search-result-import-path\">@ignavia/ella/src/Vec2.js</span>",
    "class"
  ],
  [
    "@ignavia/ella/src/vec2builder.js~vec2builder",
    "class/src/Vec2Builder.js~Vec2Builder.html",
    "<span>Vec2Builder</span> <span class=\"search-result-import-path\">@ignavia/ella/src/Vec2Builder.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/vec2.js",
    "file/src/Vec2.js.html",
    "src/Vec2.js",
    "file"
  ],
  [
    "src/vec2.js~vec2#add",
    "class/src/Vec2.js~Vec2.html#instance-method-add",
    "src/Vec2.js~Vec2#add",
    "method"
  ],
  [
    "src/vec2.js~vec2#constructor",
    "class/src/Vec2.js~Vec2.html#instance-constructor-constructor",
    "src/Vec2.js~Vec2#constructor",
    "method"
  ],
  [
    "src/vec2.js~vec2#div",
    "class/src/Vec2.js~Vec2.html#instance-method-div",
    "src/Vec2.js~Vec2#div",
    "method"
  ],
  [
    "src/vec2.js~vec2#dot",
    "class/src/Vec2.js~Vec2.html#instance-method-dot",
    "src/Vec2.js~Vec2#dot",
    "method"
  ],
  [
    "src/vec2.js~vec2#equals",
    "class/src/Vec2.js~Vec2.html#instance-method-equals",
    "src/Vec2.js~Vec2#equals",
    "method"
  ],
  [
    "src/vec2.js~vec2#length",
    "class/src/Vec2.js~Vec2.html#instance-method-length",
    "src/Vec2.js~Vec2#length",
    "method"
  ],
  [
    "src/vec2.js~vec2#mul",
    "class/src/Vec2.js~Vec2.html#instance-method-mul",
    "src/Vec2.js~Vec2#mul",
    "method"
  ],
  [
    "src/vec2.js~vec2#normalize",
    "class/src/Vec2.js~Vec2.html#instance-method-normalize",
    "src/Vec2.js~Vec2#normalize",
    "method"
  ],
  [
    "src/vec2.js~vec2#rotate",
    "class/src/Vec2.js~Vec2.html#instance-method-rotate",
    "src/Vec2.js~Vec2#rotate",
    "method"
  ],
  [
    "src/vec2.js~vec2#sub",
    "class/src/Vec2.js~Vec2.html#instance-method-sub",
    "src/Vec2.js~Vec2#sub",
    "method"
  ],
  [
    "src/vec2.js~vec2#tojson",
    "class/src/Vec2.js~Vec2.html#instance-method-toJSON",
    "src/Vec2.js~Vec2#toJSON",
    "method"
  ],
  [
    "src/vec2.js~vec2#tostring",
    "class/src/Vec2.js~Vec2.html#instance-method-toString",
    "src/Vec2.js~Vec2#toString",
    "method"
  ],
  [
    "src/vec2.js~vec2#x",
    "class/src/Vec2.js~Vec2.html#instance-member-x",
    "src/Vec2.js~Vec2#x",
    "member"
  ],
  [
    "src/vec2.js~vec2#y",
    "class/src/Vec2.js~Vec2.html#instance-member-y",
    "src/Vec2.js~Vec2#y",
    "member"
  ],
  [
    "src/vec2.js~vec2.fromjson",
    "class/src/Vec2.js~Vec2.html#static-method-fromJSON",
    "src/Vec2.js~Vec2.fromJSON",
    "method"
  ],
  [
    "src/vec2builder.js",
    "file/src/Vec2Builder.js.html",
    "src/Vec2Builder.js",
    "file"
  ],
  [
    "src/vec2builder.js~vec2builder#add",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-add",
    "src/Vec2Builder.js~Vec2Builder#add",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#constructor",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-constructor-constructor",
    "src/Vec2Builder.js~Vec2Builder#constructor",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#div",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-div",
    "src/Vec2Builder.js~Vec2Builder#div",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#dot",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-dot",
    "src/Vec2Builder.js~Vec2Builder#dot",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#equals",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-equals",
    "src/Vec2Builder.js~Vec2Builder#equals",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#length",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-length",
    "src/Vec2Builder.js~Vec2Builder#length",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#mul",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-mul",
    "src/Vec2Builder.js~Vec2Builder#mul",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#normalize",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-normalize",
    "src/Vec2Builder.js~Vec2Builder#normalize",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#rotate",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-rotate",
    "src/Vec2Builder.js~Vec2Builder#rotate",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#sub",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-sub",
    "src/Vec2Builder.js~Vec2Builder#sub",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#tojson",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-toJSON",
    "src/Vec2Builder.js~Vec2Builder#toJSON",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#tostring",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-toString",
    "src/Vec2Builder.js~Vec2Builder#toString",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#tovec2",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-method-toVec2",
    "src/Vec2Builder.js~Vec2Builder#toVec2",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder#x",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-member-x",
    "src/Vec2Builder.js~Vec2Builder#x",
    "member"
  ],
  [
    "src/vec2builder.js~vec2builder#y",
    "class/src/Vec2Builder.js~Vec2Builder.html#instance-member-y",
    "src/Vec2Builder.js~Vec2Builder#y",
    "member"
  ],
  [
    "src/vec2builder.js~vec2builder.fromjson",
    "class/src/Vec2Builder.js~Vec2Builder.html#static-method-fromJSON",
    "src/Vec2Builder.js~Vec2Builder.fromJSON",
    "method"
  ],
  [
    "src/vec2builder.js~vec2builder.fromvec2",
    "class/src/Vec2Builder.js~Vec2Builder.html#static-method-fromVec2",
    "src/Vec2Builder.js~Vec2Builder.fromVec2",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]